--- Exercise 1:
SELECT NAME FROM CITY
WHERE  COUNTRYCODE = 'USA'
AND POPULATION > 120000
--- Exercise 2: 
SELECT * FROM CITY 
WHERE COUNTRYCODE = 'JPN'
--- Exercise 3:
SELECT CITY,STATE FROM STATION
--- Exercise 4:
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE 'a%' OR CITY LIKE 'e%' OR CITY LIKE 'i%' OR CITY LIKE 'o%' OR CITY LIKE 'u%'
--- Exercise 5:
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u'
--- Exercise 6:
SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT LIKE 'a%'
AND CITY NOT LIKE 'e%'
AND CITY NOT LIKE 'i%'
AND CITY NOT LIKE 'o%'
AND CITY NOT LIKE 'U%'
--- Exercise 7:
SELECT NAME FROM EMPLOYEE
ORDER BY NAME ASC
--- Exercise 8:
SELECT NAME FROM EMPLOYEE
WHERE SALARY > 2000 AND MONTHS < 10
ORDER BY EMPLOYEE_ID ASC
--- Exercise 9:
SELECT PRODUCT_ID FROM PRODUCTS
WHERE LOW_FATS = 'Y'
AND RECYCLABLE = 'Y'
--- Exercise 10:
SELECT NAME FROM CUSTOMER
WHERE REFEREE_ID != 2 OR REFEREE_ID IS NULL
--- Exercise 11:
SELECT NAME, POPULATION,AREA FROM WORLD
WHERE AREA >= 3 AND POPULATION >=25000000
--- Exercise 12:
ELECT DISTINCT AUTHOR_ID AS ID FROM VIEWS
WHERE AUTHOR_ID = VIEWER_ID
ORDER BY ID ASC
--- Exercise 13:
SELECT DISTINCT part FROM parts_assembly
WHERE finish_date IS NULL 
--- Exercise 14:
select * from lyft_drivers
where yearly_salary <= 30000 or yearly_salary >= 70000
--- Exercise 15:
select advertising_channel from uber_advertising
where money_spent > 100000 and year = 2019
