---Exercise 1:
SELECT NAME
FROM STUDENTS 
WHERE MARKS > 75
ORDER BY RIGHT(NAME,3),ID
---Exercise 2:
SELECT USER_ID,
CONCAT (UPPER (LEFT (NAME,1)), LOWER (SUBSTRING(NAME FROM 2 FOR LENGTH(NAME)-1))) AS NAME
FROM USERS
ORDER BY USER_ID
---Exercise 3:
SELECT MANUFACTURER,
'$' || ROUND(SUM(TOTAL_SALES) /1000000,0) || ' million' AS SALES_MIL
FROM pharmacy_sales
GROUP BY MANUFACTURER
ORDER BY  ROUND(SUM(TOTAL_SALES) /1000000,0) DESC, MANUFACTURER DESC
---Exercise 4:
---Exercise 5:
---Exercise 6:
---Exercise 7:
---Exercise 8:
---Exercise 9:
---Exercise 10:
